apiVersion: v1
kind: Namespace
metadata:
  name: nextjs-app
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: nextjs-app
  name: nextjs-agent-role
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps", "secrets", "endpoints"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets", "statefulsets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nextjs-agent-binding
  namespace: nextjs-app
subjects:
  - kind: ServiceAccount
    name: gitlab-agent
    namespace: gitlab-agent
roleRef:
  kind: Role
  name: nextjs-agent-role
  apiGroup: rbac.authorization.k8s.io
